title: Shopee Label Printer
description: Imprima etiquetas de envio da Shopee direto na sua impressora térmica em modo RAW
url: https://brunotrolo.github.io/Shopee_Printer
repository: brunotrolo/Shopee_Printer
theme: jekyll-theme-minimal

# Sidebar
show_downloads: false

# Footer
footer_text: "Desenvolvido com ❤️ em Python"
